# Loading the data
  - Link of the data: https://archive.ics.uci.edu/dataset/502/online+retail+ii

**Libraries used**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Loading**

In [ ]:
# To upload the data use this command
# recommended to Compress the files before uploading

# from google.colab import files
# upload = files.upload()

In [ ]:
# unzipping files
"""
!unzip <file_name> -d <destination_folder>
"""

'\n!unzip <file_name> -d <destination_folder>\n'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Change based on your case
!unzip /content/drive/MyDrive/online+retail+ii.zip -d /content/

Archive:  /content/drive/MyDrive/online+retail+ii.zip
replace /content/online_retail_II.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
 extracting: /content/online_retail_II.xlsx

In [ ]:
# !ls /content/drive/MyDrive

In [ ]:
!ls

drive  online_retail_II.xlsx  sample_data

In [ ]:
data = pd.read_excel("online_retail_II.xlsx")
data.shape

(525461, 8)

# Inspecting

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [ ]:
data.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
343294,522911,22075,6 RIBBONS ELEGANT CHRISTMAS,24,2010-09-17 13:38:00,1.65,14748.0,United Kingdom
383356,526230,21430,SET/3 RED GINGHAM ROSE STORAGE BOX,4,2010-10-10 15:27:00,3.75,13362.0,United Kingdom
381074,526109,20723,STRAWBERRY CHARLOTTE BAG,20,2010-10-08 12:58:00,2.51,NaN,United Kingdom
189188,507373,22058,CERAMIC LOVE HEARTS DESIGN MUG,1,2010-05-09 10:47:00,1.49,13595.0,United Kingdom
40059,492757,85053,FRENCH ENAMEL CANDLEHOLDER,6,2009-12-18 14:08:00,2.10,NaN,EIRE

**Initial Statistics**

In [ ]:
data.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

**Columns**

In [ ]:
data.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

**Count of Null values**

In [ ]:
# Count of null value
data.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [ ]:
data.isna().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

**Get unique Values**

In [ ]:
# Function to get the uniqe values and their number
def get_uniques(col):

  print(f"\nUnique values in {col}: \n{data[col].unique()}")

  print(f"\nNumber of Unique values: {data[col].nunique()}")

#Choose = input("""Choose from ['Invoice', 'StockCode', 'Description', 'Quantity',
# 'InvoiceDate','Price', 'Customer ID', 'Country']\n""")

Choose = "Country"
get_uniques(Choose)

Unique values in Country:
['United Kingdom' 'France' 'USA' 'Belgium' 'Australia' 'EIRE' 'Germany'
 'Portugal' 'Japan' 'Denmark' 'Nigeria' 'Netherlands' 'Poland' 'Spain'
 'Channel Islands' 'Italy' 'Cyprus' 'Greece' 'Norway' 'Austria' 'Sweden'
 'United Arab Emirates' 'Finland' 'Switzerland' 'Unspecified' 'Malta'
 'Bahrain' 'RSA' 'Bermuda' 'Hong Kong' 'Singapore' 'Thailand' 'Israel'
 'Lithuania' 'West Indies' 'Lebanon' 'Korea' 'Brazil' 'Canada' 'Iceland']

Number of Unique values: 40

In [ ]:
# as we can see in the data their is NaN
# Which stand for Not a Number that works as a placeholder
# to check that NaN you can use isnull function
data[data['Invoice'] == 513574]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
249734,513574,22178,VICTORIAN GLASS HANGING T-LIGHT,3,2010-06-25 15:13:00,2.51,NaN,United Kingdom
249735,513574,22185,SLATE TILE NATURAL HANGING,2,2010-06-25 15:13:00,3.36,NaN,United Kingdom
249736,513574,22435,SET OF 9 HEART SHAPED BALLOONS,10,2010-06-25 15:13:00,1.06,NaN,United Kingdom
249737,513574,21042,RED SPOTTY APRON,3,2010-06-25 15:13:00,4.65,NaN,United Kingdom
249738,513574,47567B,TEA TIME KITCHEN APRON,3,2010-06-25 15:13:00,4.65,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
250244,513574,22457,NATURAL SLATE HEART CHALKBOARD,3,2010-06-25 15:13:00,5.91,NaN,United Kingdom
250245,513574,22458,CAST IRON HOOK GARDEN FORK,1,2010-06-25 15:13:00,5.06,NaN,United Kingdom
250246,513574,22459,CAST IRON HOOK GARDEN TROWEL,1,2010-06-25 15:13:00,5.06,NaN,United Kingdom
250247,513574,22464,HANGING METAL HEART LANTERN,1,2010-06-25 15:13:00,3.36,NaN,United Kingdom
250248,513574,22469,HEART OF WICKER SMALL,17,2010-06-25 15:13:00,3.36,NaN,United Kingdom

In [ ]:
data.nunique()

Invoice        28816
StockCode       4632
Description     4681
Quantity         825
InvoiceDate    25296
Price           1606
Customer ID     4383
Country           40
dtype: int64

In [ ]:
data.shape

(525461, 8)

# Initial preprocessing

**Duplicates Handling**

In [ ]:
# Number of duplicates
data.duplicated().sum()

np.int64(6865)

In [ ]:
data.drop_duplicates(inplace=True) # inplace argument means apply the changes to the dataframe

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.shape

(518596, 8)

In [ ]:
# checking the deleted rows due to duplication
525461 - 518596

6865

**Canceled purchases**
  - Canceled purchases start With C in ["Invoice"] or probably with negative value in ["Quantity"]
  - might have Negative price

In [ ]:
data[data["Quantity"] < 0].value_counts().sum()

np.int64(9816)

In [ ]:
data['Invoice'].str.contains("c").value_counts().sum()

np.int64(10185)

In [ ]:
data['Invoice'].str.startswith("c").value_counts().sum()

np.int64(10185)

In [ ]:
data[(data['Invoice'].str.startswith("C")) & (data["Quantity"] < 0)].value_counts().sum()

np.int64(9816)

In [ ]:
filtered_data = data[(data['Invoice'].str.startswith("C")) & (data["Quantity"] < 0)]

print(len(filtered_data))

10181

In [ ]:
# "Keep rows that are NOT (C-invoice OR negative quantity)"
data = data[~((data['Invoice'].str.startswith("C", na=False)) | (data["Quantity"] < 0))]

In [ ]:
data.shape

(506293, 8)

In [ ]:
518596 - 506293

12303

In [ ]:
# summary statistics to ensure Quantity min is > 0

print(data['Quantity'].describe())
print()

# Confirm no canceled invoices
remaining_canceled = data['Invoice'].str.startswith("C").sum()
print(f"Remaining canceled invoices: {remaining_canceled}")

count    506293.000000
mean         11.836229
std          93.591820
min           1.000000
25%           1.000000
50%           3.000000
75%          12.000000
max       19152.000000
Name: Quantity, dtype: float64

Remaining canceled invoices: 0

In [ ]:
data.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,506293.000000,506293,506293.000000,400947.000000
mean,11.836229,2010-06-28 16:27:08.339914240,3.991056,15361.454639
min,1.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 13:38:00,1.250000,13985.000000
50%,3.000000,2010-07-06 14:05:00,2.100000,15311.000000
75%,12.000000,2010-10-15 13:21:00,4.210000,16805.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,93.591820,NaN,128.813062,1680.669487

**Negtive in Price Column**
  - Checking why there is a negative value in price column

In [ ]:
data[data["Price"] < 0].value_counts().sum()

np.int64(0)

In [ ]:
# Rows with negative nubmers
negative_prices = data[data["Price"] < 0]
negative_prices

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

In [ ]:
# Keep only rows where Price is positive
data = data[data["Price"] > 0]

# Verify they are removed
print(f"Remaining negative prices: {len(data[data['Price'] < 0])}")

Remaining negative prices: 0

**Data after**
- Removing dublicates
- Removing canceled invoices
- Removing 3 entries of negative prices

In [ ]:
# data shape before processing (525461, 8)
data.shape

(504730, 8)