# 1 - Loading the data
  - Link of the data: https://archive.ics.uci.edu/dataset/502/online+retail+ii

## Information
  Additional Information

  This Online Retail II data set contains all the transactions occurring for a UK-based and registered, non-store online retail between 01/12/2009 and 09/12/2011.The company mainly sells unique all-occasion gift-ware. Many customers of the company are wholesalers.

  **Additional Variable Information**

  **InvoiceNo:** Invoice number. Nominal. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'c', it indicates a cancellation.

  **StockCode:** Product (item) code. Nominal. A 5-digit integral number uniquely assigned to each distinct product.

  **Description:** Product (item) name. Nominal.

  **Quantity:** The quantities of each product (item) per transaction. Numeric.

  **InvoiceDate:** Invice date and time. Numeric. The day and time when a transaction was generated.

  **UnitPrice:** Unit price. Numeric. Product price per unit in sterling (Â£).
  
  **CustomerID:** Customer number. Nominal. A 5-digit integral number uniquely assigned to each customer.

  **Country:** Country name. Nominal. The name of the country where a customer resides.

**Libraries used**

In [462]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Loading**

In [463]:
# To upload the data use this command
# recommended to Compress the files before uploading

# from google.colab import files
# upload = files.upload()

In [464]:
# unzipping files
"""
!unzip <file_name> -d <destination_folder>
"""

'\n!unzip <file_name> -d <destination_folder>\n'

In [465]:
#from google.colab import drive
#drive.mount('/content/drive')

In [466]:
# Change based on your case
#!unzip /content/drive/MyDrive/online+retail+ii.zip -d /content/

In [467]:
# !ls /content/drive/MyDrive

In [468]:
!ls

cleaned_online_retail.csv  drive  online_retail_II.xlsx  sample_data

In [469]:
data = pd.read_excel("online_retail_II.xlsx")
data.shape

(525461, 8)

# 2 - Inspecting

In [470]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [471]:
data.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
143351,502994,22297,HEART IVORY TRELLIS SMALL,1,2010-03-29 14:58:00,2.51,NaN,United Kingdom
323799,520903,21174,POTTERING IN THE SHED METAL SIGN,12,2010-09-01 10:13:00,1.95,16607.0,United Kingdom
90192,497912,85017B,ENVELOPE 50 BLOSSOM IMAGES,5,2010-02-14 14:35:00,0.85,12867.0,United Kingdom
422404,529811,20975,12 PENCILS SMALL TUBE RED RETROSPOT,3,2010-10-31 11:06:00,0.65,15569.0,United Kingdom
405770,528179,22942,CHRISTMAS LIGHTS 10 SANTAS,1,2010-10-21 10:49:00,8.50,14227.0,United Kingdom

**Initial Statistics**

In [472]:
data.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

**Columns**

In [473]:
data.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

**Count of Null values**

In [474]:
# Count of null value
data.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [475]:
data.isna().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [476]:
# Filter for null Descriptions
missing_descriptions = data[data['Description'].isnull()]
missing_descriptions.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [477]:
# Filter for Custormer ID
missing_customer_id = data[data['Customer ID'].isnull()]
missing_customer_id.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom

**Get unique Values**

In [478]:
# Function to get the uniqe values and their number
def get_uniques(col):

  print(f"\nUnique values in {col}: \n{data[col].unique()}")

  print(f"\nNumber of Unique values: {data[col].nunique()}")

#Choose = input("""Choose from ['Invoice', 'StockCode', 'Description', 'Quantity',
# 'InvoiceDate','Price', 'Customer ID', 'Country']\n""")

Choose = "Country"
get_uniques(Choose)

Unique values in Country:
['United Kingdom' 'France' 'USA' 'Belgium' 'Australia' 'EIRE' 'Germany'
 'Portugal' 'Japan' 'Denmark' 'Nigeria' 'Netherlands' 'Poland' 'Spain'
 'Channel Islands' 'Italy' 'Cyprus' 'Greece' 'Norway' 'Austria' 'Sweden'
 'United Arab Emirates' 'Finland' 'Switzerland' 'Unspecified' 'Malta'
 'Bahrain' 'RSA' 'Bermuda' 'Hong Kong' 'Singapore' 'Thailand' 'Israel'
 'Lithuania' 'West Indies' 'Lebanon' 'Korea' 'Brazil' 'Canada' 'Iceland']

Number of Unique values: 40

In [479]:
# as we can see in the data their is NaN
# Which stand for Not a Number that works as a placeholder
# Checking here for feature engineering in the feature or handeling NaN in Customer ID
data[data['Invoice'] == 513574]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
249734,513574,22178,VICTORIAN GLASS HANGING T-LIGHT,3,2010-06-25 15:13:00,2.51,NaN,United Kingdom
249735,513574,22185,SLATE TILE NATURAL HANGING,2,2010-06-25 15:13:00,3.36,NaN,United Kingdom
249736,513574,22435,SET OF 9 HEART SHAPED BALLOONS,10,2010-06-25 15:13:00,1.06,NaN,United Kingdom
249737,513574,21042,RED SPOTTY APRON,3,2010-06-25 15:13:00,4.65,NaN,United Kingdom
249738,513574,47567B,TEA TIME KITCHEN APRON,3,2010-06-25 15:13:00,4.65,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
250244,513574,22457,NATURAL SLATE HEART CHALKBOARD,3,2010-06-25 15:13:00,5.91,NaN,United Kingdom
250245,513574,22458,CAST IRON HOOK GARDEN FORK,1,2010-06-25 15:13:00,5.06,NaN,United Kingdom
250246,513574,22459,CAST IRON HOOK GARDEN TROWEL,1,2010-06-25 15:13:00,5.06,NaN,United Kingdom
250247,513574,22464,HANGING METAL HEART LANTERN,1,2010-06-25 15:13:00,3.36,NaN,United Kingdom
250248,513574,22469,HEART OF WICKER SMALL,17,2010-06-25 15:13:00,3.36,NaN,United Kingdom

In [480]:
data.nunique()

Invoice        28816
StockCode       4632
Description     4681
Quantity         825
InvoiceDate    25296
Price           1606
Customer ID     4383
Country           40
dtype: int64

In [481]:
data.shape

(525461, 8)

# 3 - Initial preprocessing
  - Shape of the data (525461, 8)

**Duplicates Handling**

In [482]:
# Number of duplicates
data.duplicated().sum()

np.int64(6865)

In [483]:
data.drop_duplicates(inplace=True) # inplace argument means apply the changes to the dataframe

In [484]:
data.duplicated().sum()

np.int64(0)

In [485]:
data.shape

(518596, 8)

In [486]:
# checking the deleted rows due to duplication
525461 - 518596

6865

**Canceled purchases**
  - Canceled purchases start With C in ["Invoice"] or probably with negative value in ["Quantity"]
  - might have Negative price
  - Also implicitly removing the null "Description" rows as they have negative quantity

In [487]:
data.shape

(518596, 8)

In [488]:
data[data["Quantity"] < 0].value_counts().sum()

np.int64(9816)

In [489]:
# Converting the ['Invoice column to string']
data['Invoice'] = data['Invoice'].astype(str)

In [490]:
data['Invoice'].str.contains('C').sum()

np.int64(10182)

In [491]:
data['Invoice'].str.startswith('C').sum()

np.int64(10182)

In [492]:
data[(data['Invoice'].str.startswith("C")) & (data["Quantity"] < 0)].value_counts().sum()

np.int64(9816)

In [493]:
# Checking if there is a canceled order with positive Quantity
data[(data['Invoice'].str.startswith("C")) & (data["Quantity"] >= 0)].value_counts().sum()

np.int64(0)

In [494]:
filtered_data = data[(data['Invoice'].str.startswith("C")) & (data["Quantity"] < 0)]

print(len(filtered_data))

10181

In [495]:
# Keeping the rows that are NOT Canceled invoices OR negative quantity
# this will remove the Missing description Rows as we dont need them
data = data[~((data['Invoice'].str.startswith("C", na=False)) | (data["Quantity"] < 0))]

In [496]:
data.shape

(506293, 8)

In [497]:
# summary statistics to ensure Quantity min is > 0

print(data['Quantity'].describe())
print()

# Confirm no canceled invoices
remaining_canceled = data['Invoice'].str.startswith('C').sum()
print(f"Remaining canceled invoices: {remaining_canceled}")

count    506293.000000
mean         11.836229
std          93.591820
min           1.000000
25%           1.000000
50%           3.000000
75%          12.000000
max       19152.000000
Name: Quantity, dtype: float64

Remaining canceled invoices: 0

In [498]:
data.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,506293.000000,506293,506293.000000,400947.000000
mean,11.836229,2010-06-28 16:27:08.339914240,3.991056,15361.454639
min,1.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 13:38:00,1.250000,13985.000000
50%,3.000000,2010-07-06 14:05:00,2.100000,15311.000000
75%,12.000000,2010-10-15 13:21:00,4.210000,16805.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,93.591820,NaN,128.813062,1680.669487

**Negtive in Price Column**
  - Checking why there is a negative value in price column

In [499]:
data['Price'] = data['Price'].astype(float)

In [500]:
data[data["Price"] < 0].value_counts().sum()

np.int64(0)

In [501]:
# Rows with negative nubmers
negative_prices = data[data["Price"] < 0]
negative_prices

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

In [502]:
# Keep only rows where Price is positive
data = data[data["Price"] > 0]

# Verify they are removed
print(f"Remaining negative prices: {len(data[data['Price'] < 0])}")

Remaining negative prices: 0

In [503]:
# Rows with negative nubmers
negative_prices = data[data["Price"] < 0]
negative_prices

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

**Data after**
- Removing dublicates
- Removing canceled invoices
- Removing 3 entries of Adjust bad debt
- Missing Description where removed due to strictly keeping the data that its quantity above **0**

In [504]:
# data shape before processing (525461, 8)
data.shape

(504730, 8)

In [505]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 504730 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      504730 non-null  object
 1   StockCode    504730 non-null  object
 2   Description  504730 non-null  object
 3   Quantity     504730 non-null  int64
 4   InvoiceDate  504730 non-null  datetime64[ns]
 5   Price        504730 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      504730 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 34.7+ MB

In [506]:
data.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,504730.000000,504730,504730.000000,400916.000000
mean,11.516944,2010-06-28 17:28:36.218374144,4.273960,15361.544074
min,1.000000,2009-12-01 07:45:00,0.001000,12346.000000
25%,1.000000,2010-03-21 14:06:15,1.250000,13985.000000
50%,3.000000,2010-07-06 14:25:00,2.100000,15311.000000
75%,12.000000,2010-10-15 13:37:00,4.210000,16805.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,87.337583,NaN,64.091288,1680.635823

In [507]:
data.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
267142,515254,22331,WOODLAND PARTY BAG + STICKER SET,1,2010-07-09 11:44:00,3.36,NaN,United Kingdom
344517,522975,72232,FENG SHUI PILLAR CANDLE,10,2010-09-19 13:37:00,0.19,16524.0,United Kingdom
283028,516924,20983,12 PENCILS TALL TUBE RED SPOTTY,3,2010-07-25 12:14:00,0.85,16400.0,United Kingdom
478284,534319,21191,LARGE WHITE HONEYCOMB PAPER BELL,3,2010-11-22 11:37:00,4.21,NaN,United Kingdom
198455,508482,22413,METAL SIGN TAKE IT OR LEAVE IT,12,2010-05-16 12:44:00,2.95,13564.0,United Kingdom

In [508]:
# Count of null value
data.isnull().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    103814
Country             0
dtype: int64

In [509]:
# Count of null value
data.isna().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    103814
Country             0
dtype: int64

## Customer ID Inspection
 - Almost 100000 missing Customer ID

In [510]:
data['Customer ID'] = data['Customer ID'].astype(float)

In [511]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 504730 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      504730 non-null  object
 1   StockCode    504730 non-null  object
 2   Description  504730 non-null  object
 3   Quantity     504730 non-null  int64
 4   InvoiceDate  504730 non-null  datetime64[ns]
 5   Price        504730 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      504730 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 34.7+ MB

In [512]:
data.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
245200,513112,22271,FELTCRAFT DOLL ROSIE,1,2010-06-21 16:28:00,2.95,17338.0,United Kingdom
514298,537240,22715,CARD WEDDING DAY,1,2010-12-06 10:08:00,0.85,NaN,United Kingdom
306437,519254,20975,12 PENCILS SMALL TUBE RED SPOTTY,24,2010-08-15 15:35:00,0.65,16422.0,United Kingdom
52216,494148,22291,"SPRING DEC , HANGING CHICK CREAM",1,2010-01-11 14:45:00,1.45,15311.0,United Kingdom
499214,536012,84050,PINK HEART SHAPE EGG FRYING PAN,6,2010-11-29 15:23:00,1.65,12351.0,Unspecified

In [513]:
# making sure of if we can create new Customer ID from their invoices
missing_customer_id = data[data['Customer ID'].isnull()]
missing_customer_id.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom

In [514]:
len(missing_customer_id)

103814

### Customer ID Imputation

In [515]:
# Total of Unique invoices
len(data['Invoice'].unique())

20951

In [516]:
# Invoices without Customer ID
len(data[data['Customer ID'].isnull()]['Invoice'].unique())

1738

**The IDEA OF THE CODE BELOW:**
 - To check if we have the same Invoice but for other Customer IDs that might exist

In [517]:
# Getting the unique list of Invoices with Missing Customer IDs
invoices_with_nans = data[data['Customer ID'].isnull()]['Invoice'].unique()

print(f"Number of invoices with missing Customer IDs: {len(invoices_with_nans)}")

# Filtering the data to get the Invoices with NaNs only all of them
subset = data[data['Invoice'].isin(invoices_with_nans)]

print(f"Number of rows in the subset: {len(subset)}")

# Tring to find ANY valid Customer IDs within this subset Created
valid_ids_found = subset['Customer ID'].dropna().unique()


print(f"Number of valid Customer IDs hiding in these invoices: {len(valid_ids_found)}")

Number of invoices with missing Customer IDs: 1738
Number of rows in the subset: 103814
Number of valid Customer IDs hiding in these invoices: 0

In [518]:
subset.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom

**Building a Customized ID**
  - After checking if we might have customer IDs based on Invoices now we can safely build a Unique ID for each missing Customer ID

**Steps**:
  1. Extracting the month and day
  2. Extracting the Invoice Number
  3. Concatenating the Invoice number with the Month and day
  4. Result is cleaned data with no missing values

In [519]:
# extracting the Month and Day as a 4 digit string
month_day_str = data['InvoiceDate'].dt.strftime('%m%d')

# Creating the Customized IDs
customized_IDs = data['Invoice'].astype(str) + month_day_str

# Using the customized IDs to fill the NaN Customer IDs
data['Customer ID'] = data['Customer ID'].fillna(customized_IDs)

print(f"Missing Customer IDs: {data['Customer ID'].isnull().sum()}")

Missing Customer IDs: 0

In [520]:
data.sample(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
261667,514643,21992,VINTAGE PAISLEY STATIONERY SET,6,2010-07-05 12:40:00,2.95,12469.0,Thailand
163783,504921,22364,GLASS JAR DIGESTIVE BISCUITS,1,2010-04-19 10:43:00,5.91,5049210419,United Kingdom
185307,507025,21370,MIRRORED WALL ART FOXY,1,2010-05-05 14:42:00,12.72,5070250505,United Kingdom
124756,501300,82581,TOILET METAL SIGN,25,2010-03-15 16:35:00,0.55,14062.0,United Kingdom
103260,499248,21934,SKULL SHOULDER BAG,10,2010-02-25 14:18:00,1.45,14298.0,United Kingdom
36952,492425,21846,PINK DIAMANTE PEN IN GIFT BOX,1,2009-12-16 17:58:00,4.30,4924251216,United Kingdom
148023,503452,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2010-04-01 11:48:00,0.21,16347.0,United Kingdom
455819,532649,35400,WOODEN BOX ADVENT CALENDAR,2,2010-11-14 10:21:00,8.95,16444.0,United Kingdom
520286,537743,22773,GREEN DRAWER KNOB ACRYLIC EDWARDIAN,12,2010-12-08 11:02:00,1.25,17706.0,United Kingdom
21668,491109,21587,COSY HOUR GIANT TUBE MATCHES,1,2009-12-09 14:30:00,2.55,13825.0,United Kingdom

# 4 - Feature Engineering
  1. Total sales
  2. Time

In [521]:
data.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
393004,527144,22113,GREY HEART HOT WATER BOTTLE,12,2010-10-15 10:21:00,3.75,14001.0,United Kingdom
483849,534709,22649,STRAWBERRY FAIRY CAKE TEAPOT,2,2010-11-23 16:53:00,11.02,5347091123,United Kingdom
180809,506559,22030,SWALLOWS GREETING CARD,24,2010-04-30 11:48:00,0.42,5065590430,EIRE
17602,490804,21292,SMALL STRIPES CHOCOLATE GIFT BAG,16,2009-12-08 12:05:00,0.85,16560.0,United Kingdom
519022,537643,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,1,2010-12-07 15:34:00,6.77,5376431207,United Kingdom

In [522]:
# Sales Column
data["Sales"] = data["Quantity"] * data["Price"]

In [523]:
data.sample(3)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Sales
169201,505448,21658,GLASS BEURRE DISH,8,2010-04-22 11:14:00,3.95,17646.0,United Kingdom,31.6
503700,536446,21587,COSY HOUR GIANT TUBE MATCHES,4,2010-12-01 12:15:00,2.55,15983.0,United Kingdom,10.2
281588,516788,22334,DINOSAUR PARTY BAG + STICKER SET,24,2010-07-23 10:00:00,1.65,16843.0,United Kingdom,39.6

In [524]:
# Time Extraction
data['Year'] = data['InvoiceDate'].dt.year
data['Month'] = data['InvoiceDate'].dt.month
data['DayOfWeek'] = data['InvoiceDate'].dt.day_name()
data['Hour'] = data['InvoiceDate'].dt.hour

data.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Sales,Year,Month,DayOfWeek,Hour
432687,530793,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-11-04 12:18:00,2.95,15910.0,United Kingdom,5.90,2010,11,Thursday,12
505524,536592,21775,DECORATIVE FLORE BATHROOM BOTTLE,3,2010-12-01 17:06:00,2.51,5365921201,United Kingdom,7.53,2010,12,Wednesday,17
134683,502248,21035,SET/2 RED SPOTTY TEA TOWELS,1,2010-03-23 14:06:00,5.91,5022480323,United Kingdom,5.91,2010,3,Tuesday,14
458067,532808,20764,ABSTRACT CIRCLES SKETCHBOOK,1,2010-11-14 15:19:00,3.75,15532.0,United Kingdom,3.75,2010,11,Sunday,15
194902,508039,16011,ANIMAL STICKERS,2,2010-05-12 12:18:00,0.21,16898.0,United Kingdom,0.42,2010,5,Wednesday,12

In [525]:
# Checking for null values
data.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Sales          0
Year           0
Month          0
DayOfWeek      0
Hour           0
dtype: int64

# Extracted Dataframe

In [526]:
"""To download the data
data.to_csv('cleaned_online_retail.csv', index=False)

from google.colab import files
files.download('cleaned_online_retail.csv')"""

"To download the data\ndata.to_csv('cleaned_online_retail.csv', index=False)\n\nfrom google.colab import files\nfiles.download('cleaned_online_retail.csv')"